"""add_membership_org_created_index

Revision ID: d98ef53f6313
Revises: 566a2159ed12
Create Date: 2026-03-10 09:58:12.853283

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d98ef53f6313"
down_revision: Union[str, None] = "566a2159ed12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_membership_org_created",
        "memberships",
        ["org_id", "created_at"],
        unique=False,
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.CHAR(length=128),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=sa.String(length=128),
        type_=sa.CHAR(length=128),
        existing_nullable=False,
    )
    op.drop_index("ix_membership_org_created", table_name="memberships")
    # ### end Alembic commands ###
